/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.79
 * Generated at: 2023-08-27 14:26:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.app.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class join_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1692876955636L));
    _jspx_dependants.put("jar:file:/Users/hidongmin37/web_1900_hds/jsp/board/src/main/webapp/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>회원가입</title>\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/css/main.css\">\n");
      out.write("<style>\n");
      out.write("	input[type='button'], input[type='submit']{border-radius: 0;}\n");
      out.write("	textarea{\n");
      out.write("	resize:none;\n");
      out.write("	}\n");
      out.write("	div.preview{overflow:hidden;}\n");
      out.write("	div.preview img{\n");
      out.write("		object-fit : cover;}\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body class=\"is-preload\">\n");
      out.write("	<!-- Page Wrapper -->\n");
      out.write("	<div id=\"page-wrapper\">\n");
      out.write("	\n");
      out.write("		<!-- Wrapper -->\n");
      out.write("		<div class=\"wrapper\">\n");
      out.write("			<div class=\"inner\">\n");
      out.write("				");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/app/fix/header.jsp", out, false);
      out.write("\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("		\n");
      out.write("		<!-- Wrapper -->\n");
      out.write("		<div class=\"wrapper\">\n");
      out.write("			<div class=\"inner\">\n");
      out.write("				<!-- Main -->	\n");
      out.write("				<section class=\"main\">\n");
      out.write("					<header class=\"major\">\n");
      out.write("						<a href=\"javascript:void(0)\" class=\"image main\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/images/join01.png\"></a>\n");
      out.write("						<h1>회원가입</h1>\n");
      out.write("						<p>\n");
      out.write("							환영합니다 고객님<br>\n");
      out.write("							회원가입 후 정상적인 서비스를 이용하실 수 있습니다.\n");
      out.write("						</p>\n");
      out.write("					</header>\n");
      out.write("					<hr>\n");
      out.write("					<form method=\"post\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/joinOk.me\" name=\"joinForm\" id=\"\">\n");
      out.write("						<div style=\"display:flex; justify-content:space-around;\">\n");
      out.write("							<div style=\"width:40%;\">\n");
      out.write("								<p style=\"background:#fd3a3a2e;\">\n");
      out.write("									<span style=\"color:red; font-size:2rem; font-weight:bold;\">*</span>\n");
      out.write("									아래 항목은 모두 작성해주세요.\n");
      out.write("								</p>\n");
      out.write("								<div>\n");
      out.write("									<div class=\"col-6 col-12-xsmall\" style=\"width:100%\">\n");
      out.write("										<p style=\"margin:0\">\n");
      out.write("											아이디<span id=\"idCheck_text\" style=\"font-size:0.7em\"></span>\n");
      out.write("										</p>\n");
      out.write("										<input type=\"text\" name=\"memberId\" id=\"memberId\" value=\"\" placeholder=\"6자 이상의 영문 혹은 영문과 숫자를 조합\"/>\n");
      out.write("										<br>\n");
      out.write("										<p style=\"margin:0\">비밀번호</p>\n");
      out.write("										<input type=\"password\" name=\"memberPw\" id=\"memberPw\" value=\"\" placeholder=\"영문 4자 이상, 최대 20자\"/>\n");
      out.write("										<br>\n");
      out.write("										<div style=\"display:flex; justify-content:space-between;\">\n");
      out.write("											<div style=\"width:48%\">\n");
      out.write("												<p style=\"margin:0\">이름</p>\n");
      out.write("												<input type=\"text\" name=\"memberName\" id=\"memberName\"/>\n");
      out.write("											</div>\n");
      out.write("											<div style=\"width:48%\">\n");
      out.write("												<p style=\"margin:0\">나이</p>\n");
      out.write("												<input type=\"text\" name=\"memberAge\" id=\"memberAge\"/>\n");
      out.write("											</div>\n");
      out.write("										</div>		\n");
      out.write("										<hr>\n");
      out.write("										<div style=\"margin-top: 6%;margin-bottom: 6%;\">\n");
      out.write("											<input type=\"checkbox\" id=\"term\" name=\"term\">\n");
      out.write("											<label for=\"term\" style=\"font-size:1.1em; font-weight: bold;\">전체 동의합니다.</label>\n");
      out.write("										</div>							\n");
      out.write("										<div class=\"col-12\" style=\"display:flex; justify-content: space-between\">\n");
      out.write("											<div>\n");
      out.write("												<input type=\"checkbox\" id=\"term1\" name=\"term1\" class=\"terms\">\n");
      out.write("												<label for=\"term1\">서비스 이용약관</label>\n");
      out.write("											</div>\n");
      out.write("											<div class=\"term-detail\">\n");
      out.write("												<a href=\"term1-content\">펼쳐보기</a>\n");
      out.write("											</div>\n");
      out.write("										</div>\n");
      out.write("										<textarea name=\"term1-content\" id=\"term1-content\" rows=\"3\" style=\"display: none\" \n");
      out.write("										readonly=\"readonly\"></textarea>\n");
      out.write("										<br>\n");
      out.write("										<div class=\"col-12\" style=\"display:flex; justify-content: space-between\">\n");
      out.write("											<div>\n");
      out.write("												<input type=\"checkbox\" id=\"term2\" name=\"term2\" class=\"terms\">\n");
      out.write("												<label for=\"term2\">개인정보 수집 및 이용</label>\n");
      out.write("											</div>\n");
      out.write("											<div class=\"term-detail\">\n");
      out.write("												<a href=\"term2-content\">펼쳐보기</a>\n");
      out.write("											</div>\n");
      out.write("										</div>\n");
      out.write("										<textarea name=\"term2-content\" id=\"term2-content\" rows=\"3\" style=\"display: none\" \n");
      out.write("										readonly=\"readonly\"></textarea>\n");
      out.write("										<br>	\n");
      out.write("									</div>\n");
      out.write("								</div>\n");
      out.write("								<hr>\n");
      out.write("								<p style=\"background:#3a5afd2e;\">\n");
      out.write("								아래 항목은 선택 사항입니다.\n");
      out.write("								</p>\n");
      out.write("								<p style=\"margin: 0\">성별</p>\n");
      out.write("								<div class=\"col-4 col-12-small\">\n");
      out.write("									<input type=\"radio\" id =\"male\" name=\"memberGender\" value=\"남자\" >\n");
      out.write("									<label for=\"male\">남자</label>\n");
      out.write("									<input type=\"radio\" id =\"female\" name=\"memberGender\" value=\"여자\" >\n");
      out.write("									<label for=\"female\">여자</label>\n");
      out.write("									<input type=\"radio\" id =\"none\" name=\"memberGender\" value=\"선택안함\" checked>\n");
      out.write("									<label for=\"none\">선택안함</label>\n");
      out.write("								</div>\n");
      out.write("								<p style=\"margin:0;\">이메일</p>\n");
      out.write("								<input type=\"email\" name=\"memberEmail\" id=\"memberEmail\" value=\"\">\n");
      out.write("								<br>\n");
      out.write("								<p style=\"margin:0;\">우편번호</p>\n");
      out.write("								<div style=\"display: flex;justify-content: space-between;\">\n");
      out.write("									<input type=\"text\" name=\"memberZipcode\" class=\"postcodify_postcode5\" value=\"\">\n");
      out.write("									<ul class=\"actions\">\n");
      out.write("										<li>\n");
      out.write("											<input type=\"button\" id=\"postcodify_search_button\" class=\"button primary\" style=\"border-radius: 0;\" value=\"검색\">\n");
      out.write("										<li>\n");
      out.write("									</ul>\n");
      out.write("								</div>\n");
      out.write("								<p style=\"margin:0\">주소</p>\n");
      out.write("								<input type=\"text\" name=\"memberAddress\" id=\"memberAddress\" class=\"postcodify_address\" value=\"\">\n");
      out.write("								<br>\n");
      out.write("								<p style=\"margin:0\">상세주소</p>\n");
      out.write("								<input type=\"text\" name=\"memberAddressDetail\" id=\"memberAddressDetail\" class=\"postcodify_details\" value=\"\">\n");
      out.write("								<br>\n");
      out.write("								<p style=\"margin:0\">참고항목</p>\n");
      out.write("								<input type=\"text\" name=\"memberAddressEtc\" id=\"memberAddressEtc\" class=\"postcodify_extra_info\" value=\"\">\n");
      out.write("								<br>\n");
      out.write("								<div class=\"col-12\" style=\"margin-top:8%\">\n");
      out.write("									<ul class=\"actions\" style=\"display:felx;justify-content: center;\">\n");
      out.write("										<li>\n");
      out.write("											<input type=\"button\" value=\"완료\" class=\"primary\" onclick=\"formSubmit()\">\n");
      out.write("										</li>\n");
      out.write("										<li>\n");
      out.write("											<input type=\"button\" value=\"취소\" class=\"primary\" onclick=\"history.back()\">\n");
      out.write("										</li>\n");
      out.write("									</ul>\n");
      out.write("								</div>\n");
      out.write("							</div>\n");
      out.write("							\n");
      out.write("							<div class=\"preview\" style=\"width:40%;\">\n");
      out.write("								<div>\n");
      out.write("									<h4>광고1</h4>\n");
      out.write("									<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/images/ex01.png\" >\n");
      out.write("								</div>\n");
      out.write("								<hr>\n");
      out.write("								<div>\n");
      out.write("									<h4>광고2</h4>\n");
      out.write("									<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/images/ex02.png\" >\n");
      out.write("								</div>\n");
      out.write("								<hr>\n");
      out.write("								<div>\n");
      out.write("									<h4>광고3</h4>\n");
      out.write("									<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/images/ex03.png\">\n");
      out.write("								</div>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("					</form>\n");
      out.write("				</section>\n");
      out.write("			</div>\n");
      out.write("		</div>		\n");
      out.write("	</div>\n");
      out.write("</body>\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/js/jquery.min.js\"></script>\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/js/browser.min.js\"></script>\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/js/breakpoints.min.js\"></script>\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/js/util.js\"></script>\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/js/main.js\"></script>\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/js/join.js\"></script>\n");
      out.write("<script src=\"//d1p7wdleee1q2z.cloudfront.net/post/search.min.js\"></script>\n");
      out.write("<script> $(function() { $(\"#postcodify_search_button\").postcodifyPopUp(); }); </script>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
