/*
 * 
 * 
 * 
 */

DELETE FROM PLAYER WHERE "POSITION"='MF';

DELETE FROM PLAYER WHERE HEIGHT >=180;

/*NULL*/
SELECT * FROM TBL_CAR;

ALTER TABLE TBL_CAR MODIFY CAR_BRAND NOT NULL;

ALTER TABLE TBL_CAR DROP CONSTRAINT SYS_C0026439;

SELECT * FROM PLAYER WHERE NICKNAME IS NULL;
SELECT * FROM PLAYER WHERE "POSITION" IS NULL;
SELECT PLAYER_NAME,NVL(NICKNAME,'없음') FROM PLAYER;

SELECT PLAYER_NAME,NVL("POSITION",'미정') FROM PLAYER;

SELECT PLAYER_NAME,NVL2(NATION,'등록','미등록') FROM PLAYER;

SELECT PLAYER_NAME "선수 이름" ,BIRTH_DATE AS 생일 FROM PLAYER;

SELECT BACK_NO "등 번호", NICKNAME "선수 별명" FROM PLAYER;

SELECT PLAYER_NAME || '의 별명은' || NICKNAME || '이다.' "자기 소개" FROM PLAYER;

SELECT PLAYER_NAME || '의 영어이름' ||  || '입니다.' "자기 소개" FROM PLAYER;

SELECT PLAYER_NAME || '의 영어이름' || E_PLAYER_NAME || NVL2(E_PLAYER_NAME, '입니다.','없습니다') "자기 소개" FROM PLAYER;


/*
 * LIKE: 포함된 문자열 값을 찾고, 문자의 개수도 제한을 줄 수 있다.
 * 
 * WHERE [컬럼명] LIKE '서식';
 * 
 * % : 모든 것
 * _ : 글자 수
 * 
 * 예)
 * 
 * '%A' : A로 끝나는 모든 것.
 * 'A%' : A로 시작하는 모든 것.
 * '%A%' : A포함
 * 'A__' :A로 시작하는 3글자
 * '_A' : A로 끝나는 2 글
 * 
 * */

/*
 * 천마로 끝나는 팀 이름 찾
 * */

SELECT * FROM TEAM WHERE TEAM_NAME LIKE '%천마';

/*
 * 집계함수는 NULL값을 포함하지 않는다.
 * */

SELECT * FROM PLAYER WHERE LIKE '김%';
SELECT * FROM PLAYER WHERE LIKE '김_';
SELECT * FROM PLAYER WHERE LIKE '김%' OR LIKE '이%';
SELECT * FROM PLAYER WHERE NOT LIKE  '이%';

SELECT COUNT(NVL(HEIGHT,0)) FROM PLAYER;

SELECT "POSITION" WHERE WEIGHT >=80 HAVING  AVG(HEIGHT)>=180 GROUP BY "POSITION" FROM PLAYER

SELECT JOB_ID HAVING AVG(SALARY)< 1000 GROUP BY JOB_ID ORDER BY JOB_ID ASC FROM EMPLOYEES
