
CREATE TABLE TBL_FLOWER(
	/*
	FLOWER_NAME VARCHAR2(1000) CONSTRAINT PK_FLOWER PRIMARY KEY,
	FLOWER_COLOR VARCHAR2(1000) CONSTRAINT PK_FLOWER PRIMARY KEY,
	위와 같은 경우에는 오류가 나옴.
	*/
	FLOWER_NAME VARCHAR2(1000),
	FLOWER_COLOR VARCHAR2(1000),
	FLOWER_PRICE NUMBER,
	FLOWER_EXPIRY_DATE DATE,
	FLOWER_STOCK NUMBER,
	FLOWER_SALE NUMBER,
	CONSTRAINT PK_FLOWER PRIMARY KEY(FLOWER_NAME,FLOWER_COLOR)
);

CREATE TABLE TBL_POT(
	POT_NUMBER NUMBER CONSTRAINT PK_POT PRIMARY KEY,
	POT_COLOR VARCHAR2(1000),
	POT_SHAPE VARCHAR2(1000),
	POT_PRICE NUMBER,
	POT_STOCK NUMBER,
	FLOWER_NAME VARCHAR2(1000),
	FLOWER_COLOR VARCHAR2(1000),
	CONSTRAINT FK_POT FOREIGN KEY(FLOWER_NAME,FLOWER_COLOR)
	REFERENCES TBL_FLOWER(FLOWER_NAME,FLOWER_COLOR)
);



CREATE TABLE TBL_OWNER (
		OWNER_PHONE_NUMBER NUMBER CONSTRAINT PK_OWNER PRIMARY KEY,
		OWNER_NAME VARCHAR2(1000),
		OWNER_AGE NUMBER,
		OWNER_ADDRESS VARCHAR2(1000)
);

CREATE TABLE TBL_PET(
	PET_PINNUMBER NUMBER CONSTRAINT PK_PET PRIMARY KEY,
	PET_KIND VARCHAR2(1000),
	PET_NAME VARCHAR2(1000),
	PET_AGE NUMBER,
	PET_DISEASE_NAME VARCHAR2(1000),
	OWNER_PHONE_NUMBER NUMBER,
	CONSTRAINT FK_PET FOREIGN KEY (OWNER_PHONE_NUMBER)
	REFERENCES TBL_OWNER (OWNER_PHONE_NUMBER)
);






