/*VIEW*/
/*PLAYER 테이블에서 나이 컬럼 추가한 뷰 만들기 */

SELECT p.*,round((SYSDATE - BIRTH_DATE)/365)  FROM PLAYER p;

CREATE VIEW VIEW_PLAYER AS
SELECT p.*,round((SYSDATE - BIRTH_DATE)/365) AGE  FROM PLAYER p;


SELECT AGE FROM 	VIEW_PLAYER vp ;



SELECT e.*, FIRST_NAME || LAST_NAME || '이다' "FULL_NAME" FROM EMPLOYEES e ;

SELECT * FROM EMP e ;