/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.79
 * Generated at: 2023-09-13 14:44:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.app.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class myPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"ko\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>내 상점</title>\n");
      out.write("    <!-- 부트스트랩 -->\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx\" crossorigin=\"anonymous\">\n");
      out.write("    <!-- 부트스트랩 icon -->\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.1/font/bootstrap-icons.css\">\n");
      out.write("\n");
      out.write("    <!-- 공통 CSS -->\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/css/market/common.css\">\n");
      out.write("    <!-- 내 상점 페이지 CSS -->\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/css/market/market_my_store.css\">\n");
      out.write(" \n");
      out.write("    <!-- 파비콘 -->\n");
      out.write("    <link rel=\"icon\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/images/market/favicon.ico\">\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <!--건너뛰기 링크-->\n");
      out.write("    <a id=\"skipNav\" href=\"?????.html\">로그인/회원가입</a>\n");
      out.write("    <a id=\"skipNav\" href=\"market_my_store.html\">내 상점</a>\n");
      out.write("    <!--건너뛰기 링크 종료-->\n");
      out.write("\n");
      out.write("    <div id=\"wrapper\">\n");
      out.write("        <!-- header 영역 -->\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/app/fix/header.jsp", out, false);
      out.write("\n");
      out.write("        <!-- // header 영역 -->\n");
      out.write("\n");
      out.write("\n");
      out.write("        <!-- main_content 영역 -->\n");
      out.write("        <div id=\"main_content\">\n");
      out.write("            <!-- 내 상점명 -->\n");
      out.write("            <div id=\"my_store_area\">\n");
      out.write("                <div class=\"my_store_left\">\n");
      out.write("                    <div>\n");
      out.write("                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/images/market/store.svg\" alt=\"내 상점\">\n");
      out.write("                    </div>\n");
      out.write("                    <div>\n");
      out.write("                        <p>상점명</p>\n");
      out.write("                        <p>\n");
      out.write("                            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/images/market/star.png\" alt=\"별점\">\n");
      out.write("                            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/images/market/star.png\" alt=\"별점\">\n");
      out.write("                            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/images/market/star.png\" alt=\"별점\">\n");
      out.write("                            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/images/market/star.png\" alt=\"별점\">\n");
      out.write("                            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/images/market/star.png\" alt=\"별점\">\n");
      out.write("                        </p>\n");
      out.write("                    </div>\n");
      out.write("                    <div>\n");
      out.write("                        <p>\n");
      out.write("                            <a href=\"#\">내 상점 관리</a>\n");
      out.write("                        </p>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"my_store_right\">\n");
      out.write("                    <div id=\"my_store_right_top\">\n");
      out.write("                        <div>\n");
      out.write("                            <h2>상점명</h2>\n");
      out.write("                            <button>상점명 수정</button>\n");
      out.write("                        </div>\n");
      out.write("                        \n");
      out.write("                        <div>\n");
      out.write("                            <p><span>OK</span> 본인인증 완료</p>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <div id=\"my_store_right_mid\">\n");
      out.write("                        <div>\n");
      out.write("                            <p>\n");
      out.write("                                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/images/market/store_open.png\" alt=\"상점 오픈일\">\n");
      out.write("                            </p>\n");
      out.write("                            <p>\n");
      out.write("                                상점오픈일 <span>0 일 전</span>\n");
      out.write("                            </p>\n");
      out.write("                        </div>\n");
      out.write("                        <div>\n");
      out.write("                            <p>\n");
      out.write("                                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/images/market/people.png\" alt=\"상점 방문수\">\n");
      out.write("                            </p>\n");
      out.write("                            <p>\n");
      out.write("                                상점방문수 <span>0 명</span>\n");
      out.write("                            </p>\n");
      out.write("                        </div>\n");
      out.write("                        <div>\n");
      out.write("                            <p>\n");
      out.write("                                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/images/market/product_sell.png\" alt=\"상품판매\">\n");
      out.write("                            </p>\n");
      out.write("                            <p>\n");
      out.write("                                상품판매 <span>0 회</span>\n");
      out.write("                            </p>\n");
      out.write("                        </div>\n");
      out.write("                        <div>\n");
      out.write("                            <p>\n");
      out.write("                                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/images/market/parcel_service.png\" alt=\"택배발송\">\n");
      out.write("                            </p>\n");
      out.write("                            <p>\n");
      out.write("                                택배발송 <span>0 회</span>\n");
      out.write("                            </p>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <div id=\"my_store_right_bot\">\n");
      out.write("                        <div id=\"intro_modify\">\n");
      out.write("                            <button>소개글 수정</button>\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <div class=\"text_area\">\n");
      out.write("                            <textarea></textarea>\n");
      out.write("                            <button>확인</button>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <!-- // 내 상점명 -->\n");
      out.write("\n");
      out.write("            <!-- 내 상점 메뉴 -->\n");
      out.write("            <div id=\"my_store_menu\">\n");
      out.write("                <div class=\"container text-center menu_bar\">\n");
      out.write("                    <div class=\"row\">\n");
      out.write("                        <div class=\"col my_store_menus goods_menu\">\n");
      out.write("                            상품 <span>0</span>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"col my_store_menus review_menu\">\n");
      out.write("                            상점후기 <span>0</span>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"col my_store_menus recommend_menu\">\n");
      out.write("                            찜 <span>0</span>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"col my_store_menus following_menu\">\n");
      out.write("                            팔로워 <span>0</span>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"col my_store_menus follower_menu\">\n");
      out.write("                            팔로잉 <span>0</span>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div id=\"my_store_menu_content\">\n");
      out.write("                    <div id=\"goods_menu_area\" class=\"common_menu\">\n");
      out.write("                        <div>\n");
      out.write("                            <p>\n");
      out.write("                                상품 <span>0</span>\n");
      out.write("                            </p>\n");
      out.write("                            <ul id=\"goods_cate\">\n");
      out.write("                                <li>전체</li>\n");
      out.write("                                <li class=\"hidden_menu\">전체</li>\n");
      out.write("                            </ul>\n");
      out.write("                            <i class=\"bi bi-chevron-down under_direction under\"></i>\n");
      out.write("                        </div>\n");
      out.write("                        <div>\n");
      out.write("                            <p>\n");
      out.write("                                등록된 상품이 없습니다.\n");
      out.write("                            </p>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <div id=\"review_menu_area\" class=\"common_menu\">\n");
      out.write("                        <div>\n");
      out.write("                            <p>\n");
      out.write("                                상점후기 <span>0</span>\n");
      out.write("                            </p>\n");
      out.write("                        </div>\n");
      out.write("                        <div>\n");
      out.write("                            <p>\n");
      out.write("                                상점후기가 없습니다.\n");
      out.write("                            </p>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <div id=\"recommend_menu_area\" class=\"common_menu\">\n");
      out.write("                        <div>\n");
      out.write("                            <p>\n");
      out.write("                                찜 <span>0</span>\n");
      out.write("                            </p>\n");
      out.write("                        </div>\n");
      out.write("                        <div>\n");
      out.write("                            <p>\n");
      out.write("                                찜한 상품이 없습니다.\n");
      out.write("                            </p>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <div id=\"following_menu_area\" class=\"common_menu\">\n");
      out.write("                        <div>\n");
      out.write("                            <p>\n");
      out.write("                                팔로잉 <span>0</span>\n");
      out.write("                            </p>\n");
      out.write("                        </div>\n");
      out.write("                        <div>\n");
      out.write("                            <p>\n");
      out.write("                                아직 팔로우한 사람이 없습니다.\n");
      out.write("                            </p>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <div id=\"follower_menu_area\" class=\"common_menu\">\n");
      out.write("                        <div>\n");
      out.write("                            <p>\n");
      out.write("                                팔로워 <span>0</span>\n");
      out.write("                            </p>\n");
      out.write("                        </div>\n");
      out.write("                        <div>\n");
      out.write("                            <p>\n");
      out.write("                                아직 이 상점을 팔로우한 사람이 없습니다.\n");
      out.write("                            </p>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <!-- // 내 상점 메뉴 -->\n");
      out.write("        </div>\n");
      out.write("        <!-- // main_content 영역 -->\n");
      out.write("\n");
      out.write("\n");
      out.write("        <!-- footer 영역 -->\n");
      out.write("               ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/app/fix/footer.jsp", out, false);
      out.write("\n");
      out.write("       \n");
      out.write("        <!-- // footer 영역 -->\n");
      out.write("    </div>\n");
      out.write("</body>\n");
      out.write("  <!-- js -->\n");
      out.write("    <script>\n");
      out.write("		let contextPath = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\n");
      out.write("	</script>\n");
      out.write("	   \n");
      out.write("   \n");
      out.write("        <!-- 소개글 수정 -->\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/js/market/market_intro_modify.js\"></script>\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/js/market/jquery-3.6.0.min.js\"></script>\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/js/market/menu_hover.js\"></script>\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/js/market/login_modal.js\"></script>\n");
      out.write("    \n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
