/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.79
 * Generated at: 2023-09-23 13:28:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.app.fix;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/Users/hidongmin37/web_1900_hds/jsp/cocoProject/src/main/webapp/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1692876955000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("  <!-- header 영역 -->\n");
      out.write("        <header>\n");
      out.write("            <div id=\"top_header_bot_border\">\n");
      out.write("                <div id=\"top_header\">\n");
      out.write("                        <div class=\"container text-center\">\n");
      out.write("                            <div id=\"top_header_menu\" class=\"row justify-content-between\">\n");
      out.write("                                <div class=\"col-4 top_header_icon\">\n");
      out.write("                                    <a href=\"#\">\n");
      out.write("                                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/images/market/download.svg\" alt=\"앱 다운로드\"> 앱다운로드\n");
      out.write("                                    </a>\n");
      out.write("                                    <a href=\"#\">\n");
      out.write("                                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/images/market/bookmark.svg\" alt=\"즐겨찾기\"> 즐겨찾기\n");
      out.write("                                    </a>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"col-4\">\n");
      out.write("                                    <div class=\"row justify-content-end top_header_login\">\n");
      out.write("                                        <div class=\"col-4\">\n");
      out.write("                                            <a href=\"#\" class=\"btn_map_close\">\n");
      out.write("                                                로그인/회원가입\n");
      out.write("                                            </a>\n");
      out.write("                                        </div>\n");
      out.write("                                        <div class=\"col-4\">\n");
      out.write("                                            <a href=\"market_my_store.html\">\n");
      out.write("                                                내상점\n");
      out.write("                                            </a>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </header>\n");
      out.write("        <div id=\"bot_header_border\">\n");
      out.write("            <div id=\"bot_header\">\n");
      out.write("                <div class=\"container text-center\">\n");
      out.write("                    <div class=\"row justify-content-start\">\n");
      out.write("                        <div class=\"col-3 header_logo\">\n");
      out.write("                            <h1 class=\"hidden\">로고</h1>\n");
      out.write("                            <a href=\"/item/list.it\">\n");
      out.write("                                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/images/market/logo.svg\" alt=\"번개장터 로고\">\n");
      out.write("                            </a>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"col-6 top_searh_area\">\n");
      out.write("                            <div id=\"top_searh\">\n");
      out.write("                                <input type=\"text\" placeholder=\"상품명, 지역명, @상점명 입력\">\n");
      out.write("                                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/images/market/search.png\" alt=\"검색\">\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"col-1 b_h_left_menu\">\n");
      out.write("                            <a href=\"/item/plus.it\">\n");
      out.write("                                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/images/market/sell.png\" alt=\"판매하기\">\n");
      out.write("                                판매하기\n");
      out.write("                            </a>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"col-1 b_h_left_menu store\">\n");
      out.write("                            <a href=\"market_my_store.html\">\n");
      out.write("                                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/images/market/my_store.png\" alt=\"내상점\">\n");
      out.write("                                내상점\n");
      out.write("                            </a>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"col-1 b_h_left_menu\">\n");
      out.write("                            <a href=\"#\">\n");
      out.write("                                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/images/market/talk.png\" alt=\"번개톡\">\n");
      out.write("                                번개톡\n");
      out.write("                            </a>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"container text-center hamburger_area\">\n");
      out.write("                    <div class=\"row\">\n");
      out.write("                        <div class=\"col-md-1 hamburger\">\n");
      out.write("                            <img id=\"menu\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/images/market/hamburger.png\" alt=\"메뉴\">\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"col-md-4 sell_center\">\n");
      out.write("                            <p>\n");
      out.write("                                번개장터 판매자센터\n");
      out.write("                                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/images/market/new_img.png\" alt=\"새로워졌어요\">\n");
      out.write("                            </p>\n");
      out.write("                        </div>\n");
      out.write("                        <!-- 메뉴 호버 -->\n");
      out.write("                        <div id=\"test_area\">\n");
      out.write("                            <ul id=\"test_cates\">\n");
      out.write("                                <h2>전체 카테고리<span> ></span></h2>\n");
      out.write("                                <li id=\"clothes\"><a href=\"market_category_list.html\">의류</a></li>\n");
      out.write("                                <li id=\"acc\"><a href=\"market_category_list.html\">악세서리</a></li>\n");
      out.write("                            </ul>\n");
      out.write("                            <ul id=\"test_clos\">\n");
      out.write("                                <h3>의류</h3>\n");
      out.write("                                <li><a href=\"market_category_list.html\">남성의류</a></li>\n");
      out.write("                                <li><a href=\"market_category_list.html\">여성의류</a></li>\n");
      out.write("                            </ul>\n");
      out.write("                            <ul id=\"test_accs\">\n");
      out.write("                                <h3>악세서리</h3>\n");
      out.write("                                <li><a href=\"market_category_list.html\">시계/쥬얼리</a></li>\n");
      out.write("                                <li><a href=\"market_category_list.html\">패션 악세서리</a></li>\n");
      out.write("                            </ul>\n");
      out.write("                        </div>\n");
      out.write("                        <!-- // 메뉴 호버 -->\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div id=\"side_bar\">\n");
      out.write("                    <div id=\"heart\">\n");
      out.write("                        <p>찜한 상품</p>\n");
      out.write("                        <p><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/images/market/heart.png\" alt=\"찜 하트\"> 0</p>\n");
      out.write("                    </div>\n");
      out.write("                    <div id=\"goods\">\n");
      out.write("                        <p>최근본상품</p>\n");
      out.write("                        <p id=\"dotted\"></p>\n");
      out.write("                        <p>\n");
      out.write("                            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/images/market/eyes.png\" alt=\"눈표시\">\n");
      out.write("                            <p>최근 본 상품<br>이<br>없습니다.</p>\n");
      out.write("                        </p>\n");
      out.write("                    </div>\n");
      out.write("                    <div id=\"QR_code\">\n");
      out.write("                        <p>앱 다운로드</p>\n");
      out.write("                        <p>\n");
      out.write("                            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/images/market/QR_code.png\" alt=\"QR 코드\">\n");
      out.write("                        </p>\n");
      out.write("                    </div>\n");
      out.write("                    <div id=\"top_btn\">\n");
      out.write("                        <button>\n");
      out.write("                            <a href=\"#top_header\">TOP</a>\n");
      out.write("                        </button>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <!-- // header 영역 -->\n");
      out.write("\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
